version: 0.2

phases:
#    install:
#     runtime-versions:
#      docker: 18
#      dotnet: latest
#      linux: 3
#    commands:
#       - 'export PATH="$PATH:/root/.dotnet/tools"'
#       - 'dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider'
#       - 'dotnet codeartifact-creds install'
    pre_build:
        commands:       
            - 'export PATH="$PATH:/root/.dotnet/tools"'
            - 'dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider'
            - 'dotnet codeartifact-creds install'
            - 'dotnet nuget add source "$(aws codeartifact get-repository-endpoint --domain yoma-nuget --domain-owner 713875036202 --repository aries.cloudapi.dotnet --format nuget --query repositoryEndpoint --output text)/v3/index.json" -n "yoma-nuget/aries.cloudapi.dotnet"'           
             
    build:
        commands:
          # Build the nuget package and push it to codeartifact repository
          #- 'export PATH="$PATH:/root/.dotnet/tools"'
          #- 'dotnet pack -o .'
          - 'dotnet nuget push **/*.nupkg -s "yoma-nuget/aries.cloudapi.dotnet" -k anyapikey'        
          #- 'dotnet nuget push **/*.nupkg -s "https://yoma-nuget-713875036202.d.codeartifact.eu-west-1.amazonaws.com/nuget/aries.cloudapi.dotnet/" -k anyapikey'
artifacts:
    files:
        - '**/*'
    discard-paths: no

#---------------------------------------------------------    
